server:
  port: 8006

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9001
  cloud:
    gateway:
      routes:
        - id: api-b
          uri: lb://consumer-ribbon
          predicates:
            - Path=/api-b/**
          filters:
            - StripPrefix=1
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8801/eureka/,http://peer2:8802/eureka/
