server:
  port: 8004

spring:
  application:
    name: consumer-ribbon
  zipkin:
    base-url: http://localhost:9001

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8801/eureka/,http://peer2:8802/eureka/
