server:
  port: 8001


spring:
  application:
    name: provider
  zipkin:
    base-url: http://localhost:9001

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8801/eureka/,http://peer2:8802/eureka/
    healthcheck:
      enabled: true

